name: 'Comment Corrector'
description: 'Analyse source code for any discrepancies between a comment and the code it describes'
inputs:
  custom-words-file:
    description: 'File with a list of custom words to be added to the spell checker as recognised words'
    required: false
    default: 'undefined'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.custom-words-file }}